### ISSUE TITLE
Training with Data Distillation

### ISSUE THREAD

**Issue by BonJovi1** [ppliuboy/DDFlow#10]
Hi ppliuboy,

I have been successful in training your network on my own dataset, without any data distillation. However, I get some errors when I enable the distillation. The images I'm training on are of the dimensions (512x384) (width x height).

Kindly requesting you to help me debug this. 
Here are the changes I've made: 

In config.ini:
```
mode = train
training mode = distillation
crop_h = 384
crop_w = 512
target_h = 192
target_w = 256
```
And in ddflow_model.py, in the `create_train_op` function:
```
optim_loss = losses['census']['occlusion']+losses['distillation']['data_distillation']
.....
optim_loss = losses_['census']['occlusion']+losses_['distillation']['data_distillation']
```

Am I missing something? One thing I noticed is that one of the parameters given to the `create_train_op` function is 
```
training_mode = 'no_distillation'
```

Hope this isn't causing the issue? I'd be grateful if you could go through this error I'm getting and advise me how to proceed further. Thank you very much! 

Here's the error:
```
(DDFlow) luke.skywalker@neon:~/DDFlow$ python main.py 
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    tf.app.run() 
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 53, in main
    model.train()
  File "/home/luke.skywalker/DDFlow/ddflow_model.py", line 306, in train
    self.dataset, self.iterator = self.create_dataset_and_iterator(training_mode=self.training_mode)       
  File "/home/luke.skywalker/DDFlow/ddflow_model.py", line 99, in create_dataset_and_iterator
    shuffle=True, buffer_size=self.buffer_size, num_parallel_calls=self.num_input_threads) 
  File "/home/luke.skywalker/DDFlow/datasets.py", line 125, in create_batch_distillation_iterator
    dataset = dataset.map(self.preprocess_augmentation_distillation, num_parallel_calls=num_parallel_calls)
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 853, in map
    return ParallelMapDataset(self, map_func, num_parallel_calls)
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1870, in __init__
    super(ParallelMapDataset, self).__init__(input_dataset, map_func)
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1839, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 484, in add_to_graph
    self._create_definition_if_needed()
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 319, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 336, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1804, in tf_map_func
    ret = map_func(nested_args)
  File "/home/luke.skywalker/DDFlow/datasets.py", line 99, in preprocess_augmentation_distillation
    img1, img2, flow_fw, flow_bw, occ_fw, occ_bw = self.read_and_decode_distillation(filename_queue)
  File "/home/luke.skywalker/DDFlow/datasets.py", line 69, in read_and_decode_distillation
    flow_occ_fw_name = tf.string_join([self.fake_flow_occ_dir, '/flow_occ_fw_', filename_queue[2], '.png'])
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 597, in _slice_helper
    name=name)
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 763, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8148, in strided_slice
    name=name)
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 686, in create_op
    **kwargs)
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/luke.skywalker/virtual_environments/DDFlow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: slice index 2 of dimension 0 out of bounds. for 'strided_slice_2' (op: 'StridedSlice') with input shapes: [2], [1], [1], [1] and with computed input tensors: input[1] = <2>, input[2] = <3>, input[3] = <1>.
```
Thanks so much,
Abhinav

**Comment by ppliuboy** [comment]
There is no problem with ```optim_loss``` and ```training_mode```, because you have defined ```training_mode``` in ```config.ini```.

The error is ```flow_occ_fw_name = tf.string_join([self.fake_flow_occ_dir, '/flow_occ_fw_', filename_queue[2], '.png'])```. For the distillation mode, the ```data_list_file``` shall have three columns,  where the third column is used for distillation training to match flow and occlusion map. I guess you only have two columns (first frame and second frame).

**Comment by BonJovi1** [comment]
Hi ppliuboy,

Ah yes, silly me, it slipped my mind to make the changes in the `data_list_file` as well and append that third column. Thanks a bunch! 
I had a couple more queries, I'd be grateful if you could answer them too: 

1. So for training with data distillation, I'd have to first generate fake flow predictions for my custom dataset. Maybe I can do that using the pre-trained Flying chairs model. And then, once I have the fake flow occlusion, I can train with data distillation as we can now match flow and occlusion map. Have I gotten this right? 

2. This is more of an advice on how to train. I'm trying to fine-tune the pre-trained DDFlow model on FlyingChairs for some other custom indoor scenes. The pre-trained model is giving fantastic predictions for nearby frames, but not for far-off ones. So the flow between 1st and 2nd image is great, but the one between 1st and 5th image in the sequence is not so good. 

Could you please advise me on how to try improving the results for image frames with lesser overlap? I've already tried fine tuning the pre-trained model like this: 
```
is_restore_model = true
restore_model = ./models/FlyingChairs/data_distillation
```
and then I further trained for 40k iterations on my custom dataset with both occlusion handling and census transform, but it's still not yielding great predictions for the flow between image 1 and image 5. The further training for 40k iterations did not help much. 

Here is what my `data_list_file` looks like: 
```
./LBD/1.png ./LBD/2.png
./LBD/2.png ./LBD/1.png 
./LBD/2.png ./LBD/3.png
./LBD/3.png ./LBD/2.png 
./LBD/3.png ./LBD/4.png
./LBD/4.png ./LBD/3.png
./LBD/4.png ./LBD/5.png
./LBD/5.png ./LBD/4.png
./LBD/1.png ./LBD/3.png
./LBD/3.png ./LBD/1.png
./LBD/1.png ./LBD/4.png
./LBD/4.png ./LBD/1.png
./LBD/1.png ./LBD/5.png
./LBD/5.png ./LBD/1.png
./LBD/2.png ./LBD/4.png
./LBD/4.png ./LBD/2.png
./LBD/2.png ./LBD/5.png
./LBD/5.png ./LBD/2.png
./LBD/3.png ./LBD/5.png  
./LBD/5.png ./LBD/3.png
```
So as you can see, I'm also training for the far off frames like between 1.png and 5.png, but it's not helping much. 
Would there be anything in particular you'd recommend I do, so as to fine-tune and improve my results on image pairs with less overlap? 

Thanks a lot, and apologies for troubling you again,
Abhinav

**Comment by ppliuboy** [comment]
I suggest two directions:
- data-driven: you can collect  more image pairs with less overlap for training
- model-driven: you can modify the network structure, e.g., increase the search range when computing cost colume.

**Comment by aadilmehdis** [comment]
Hi @ppliuboy,
I wanted to clarify the modifications to be made the in the ddflow_model.py, in the create_train_op function for training with data distillation.

It is supposed to be 
```
optim_loss = losses['census']['occlusion']+losses['data_distillation']['distillation']
.....
optim_loss = losses_['census']['occlusion']+losses_['data_distillation']['distillation']
```
and not 
```
optim_loss = losses['census']['occlusion']+losses['distillation']['data_distillation']
.....
optim_loss = losses_['census']['occlusion']+losses_['distillation']['data_distillation']
```
as mentioned in the README.

The modification mentioned in README throws the following error,

```
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    tf.app.run() 
  File "/home/aadil/anaconda3/envs/DDFlow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 53, in main
    model.train()
  File "/scratch/lucifer.morningstar/DDFlow-20k/ddflow_model.py", line 313, in train
    global_step=self.global_step, regularizer_scale=self.regularizer_scale, train=True, trainable=True, is_scale=self.is_scale, training_mode=self.training_mode)
  File "/scratch/lucifer.morningstar/DDFlow-20k/ddflow_model.py", line 264, in create_train_op
    optim_loss = losses['census']['occlusion']+losses['distillation']['data_distillation']
KeyError: 'distillation'
```

Moreover, can you please tell me how I can check the warped images computed while calculating the loss with the predicted flow?

Thanks In Advance,
Aadil
