### ISSUE TITLE
ERROR：error with self.losses['abs_robust_mean']['no_occlusion']]) when train in "no_distillation" training mode

### ISSUE THREAD

**Issue by yuanxuanjing** [ppliuboy/DDFlow#19]
hello，Pengpeng
thanks for your excellent work of DDFlow and SelFlow, I have read your two papers and codes carefully, but I came across some probelms with them when I train in "no_distillation" training mode. I only config the "data_list_file" and "img_dir"  with my own dataset,  then I get some errors . By the way, I use the tensorflow version is 1.8 gpu, as the readme said.

Kindly requesting you to help me debug this.
Here are the errors:
Traceback (most recent call last):
  File "/home/siat/project/DDFlow-master/main.py", line 64, in <module>
    tf.app.run() 
  File "/home/siat/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/siat/project/DDFlow-master/main.py", line 53, in main
    model.train()
  File "/home/siat/project/DDFlow-master/ddflow_model.py", line 332, in train
    self.losses['abs_robust_mean']['no_occlusion']])
  File "/home/siat/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/siat/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/siat/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/siat/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= -63
	 [[Node: random_uniform = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0](random_uniform/shape, random_uniform/min, add)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,320,896,3], [?,320,896,3]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

My own dataset is :
train_image01_01.png train_image01_02.png 0
train_image01_02.png train_image01_03.png 1
train_image01_03.png train_image01_04.png 2
train_image01_04.png train_image01_05.png 3
train_image01_05.png train_image02_01.png 4
train_image02_01.png train_image02_02.png 5
train_image02_02.png train_image02_03.png 6
train_image02_03.png train_image03_01.png 7 

thanks so much, looking forward to your reply.

**Comment by yuanxuanjing** [comment]
and I have replace tf.extract_image_patches with another implementation, e.g.
out_channels = d * d
    w = tf.eye(out_channels*channel, dtype=tf.float32)
    w = tf.reshape(w, (d, d, channel, out_channels*channel))
    x2_patches = tf.nn.conv2d(x2_warp, w, strides=[1, 1, 1, 1], padding='SAME')
the errors still appear

**Comment by yuanxuanjing** [comment]
I have found where error is, thank you!
