### ISSUE TITLE
How did you use Flyingchairs for training?

### ISSUE THREAD

**Issue by guyibai** [ppliuboy/DDFlow#3]
FlyingChairs dataset is in PPM , but your model  seems not to support it.Which step did you use this dataset?

**Comment by ppliuboy** [comment]
https://github.com/ppliuboy/DDFlow/blob/master/datasets.py#L42

**Comment by guyibai** [comment]
> https://github.com/ppliuboy/DDFlow/blob/master/datasets.py#L42

谢谢！请问您在训练Teacher Model和Student Model时两种Loss都分别下降到了多少？在使用新的数据集finetune时我应该什么时候停止？
另外，我在使用多gpus训练进行到step 3时遇到了下面的问题，请问是什么情况？
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    tf.app.run() 
  File "/*******************/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 53, in main
    model.train()
  File "/*******************/DDFlow-master/ddflow_model.py", line 311, in train
    global_step=self.global_step, regularizer_scale=self.regularizer_scale, train=True, trainable=True, is_scale=self.is_scale, training_mode=self.training_mode)
  File "/*******************/DDFlow-master/ddflow_model.py", in create_train_op
    optim_loss = losses_['census']['occlusion']+losses_['data_distillation']
`
`
`
`
TypeError: Expected float32, got {'distillation': <tf.Tensor 'truediv_6:0' shape=() dtype=float32>} of type 'dict' instead.

**Comment by ppliuboy** [comment]
losses['data_distillation']['distillation']
