### ISSUE TITLE
ERROR: could not initialize a memory descriptor

### ISSUE THREAD

**Issue by Advocate99** [ppliuboy/DDFlow#9]
How to cope with this problem?
The environment has been settled as the ReadMe mentions.
`
2020-03-16 12:54:57.651335: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at mkl_concat_op.cc:784 : Aborted: Operation received an exception:Status: 5, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                                                     2020-03-16 12:54:57.787633: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at mkl_concat_op.cc:784 : Aborted: Operation received an exception:Status: 5, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                                                     Traceback (most recent call last):                                                                                        File "main.py", line 64, in <module>                                                                                      tf.app.run()                                                                                                          File "/home/humanflow/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run                                                                                                                        _sys.exit(main(argv))                                                                                                 File "main.py", line 53, in main                                                                                          model.train()                                                                                                         File "/home/humanflow/project/selflow/DDFlow/ddflow_model.py", line 332, in train                                         self.losses['abs_robust_mean']['no_occlusion'], self.losses['census']['occlusion']])                                  File "/home/humanflow/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run                                                                                                                      run_metadata_ptr)                                                                                                     File "/home/humanflow/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run                                                                                                                    feed_dict_tensor, options, run_metadata)                                                                              File "/home/humanflow/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run                                                                                                                 run_metadata)                                                                                                         File "/home/humanflow/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call                                                                                                                raise type(e)(node_def, op, message)                                                                                tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 5, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                 [[Node: concat_21 = _MklConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](estimator_level_2_1/conv5/Maximum, estimator_level_2_1/conv6/BiasAdd, gradients/ExtractImagePatches_grad/Reshape_1/shape/0, estimator_level_2_1/conv5/Maximum:1, estimator_level_2_1/conv6/BiasAdd:2, DMT/_279)]]                                                                                                                            Caused by op u'concat_21', defined at:                                                                                    File "main.py", line 64, in <module>                                                                                      tf.app.run()                                                                                                          File "/home/humanflow/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run                                                                                                                        _sys.exit(main(argv))                                                                                                 File "main.py", line 53, in main                                                                                          model.train()                                                                                                         File "/home/humanflow/project/selflow/DDFlow/ddflow_model.py", line 312, in train                                         global_step=self.global_step, regularizer_scale=self.regularizer_scale, train=True, trainable=True, is_scale=self.is_scale, training_mode=self.training_mode)                                                                                 File "/home/humanflow/project/selflow/DDFlow/ddflow_model.py", line 262, in create_train_op                               losses, regularizer_loss = self.build(iterator, regularizer_scale=regularizer_scale, train=train, trainable=trainable, is_scale=is_scale, training_mode=training_mode)                                                                        File "/home/humanflow/project/selflow/DDFlow/ddflow_model.py", line 253, in build                                         losses, regularizer_loss = self.build_no_data_distillation(iterator=iterator, regularizer_scale=regularizer_scale, train=train, trainable=trainable, is_scale=is_scale)                                                                       File "/home/humanflow/project/selflow/DDFlow/ddflow_model.py", line 201, in build_no_data_distillation                    train=train, trainable=trainable, reuse=None, regularizer=regularizer, is_scale=is_scale)                             File "/home/humanflow/project/selflow/DDFlow/network.py", line 130, in pyramid_processing_bidirection                     flow_bw = _pyramid_processing(x2_feature, x1_feature, img_size, train=train, trainable=trainable, reuse=True, regularizer=regularizer, is_scale=is_scale)                                                                                     File "/home/humanflow/project/selflow/DDFlow/network.py", line 112, in _pyramid_processing                                flow_estimated['refined'] = context_network(x_feature, flow_estimated['level_2'], train=train, trainable=trainable, reuse=reuse, regularizer=regularizer, name='context_network')                                                             File "/home/humanflow/project/selflow/DDFlow/network.py", line 32, in context_network                                     x_input = tf.concat([x, flow], axis=-1)                                                                               File "/home/humanflow/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1189, in concat                                                                                                                   return gen_array_ops.concat_v2(values=values, axis=axis, name=name)                                                   File "/home/humanflow/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 953, in concat_v2                                                                                                             "ConcatV2", values=values, axis=axis, name=name)                                                                      File "/home/humanflow/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper                                                                                               op_def=op_def)                                                                                                        File "/home/humanflow/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op                                                                                                                op_def=op_def)                                                                                                        File "/home/humanflow/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__                                                                                                                 self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access                                                                                                                                                          AbortedError (see above for traceback): Operation received an exception:Status: 5, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                               [[Node: concat_21 = _MklConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](estimator_level_2_1/conv5/Maximum, estimator_level_2_1/conv6/BiasAdd, gradients/ExtractImagePatches_grad/Reshape_1/shape/0, estimator_level_2_1/conv5/Maximum:1, estimator_level_2_1/conv6/BiasAdd:2, DMT/_279)]] 
`

**Comment by ppliuboy** [comment]
It seems that *tf.extract_image_patches* doesn't work for some tensorflow version. You can try replacing tf.extract_image_patches with another implementation, e.g., 

    out_channels = d * d
    w = tf.eye(out_channels*channel, dtype=tf.float32)
    w = tf.reshape(w, (d, d, channel, out_channels*channel))
    x2_patches = tf.nn.conv2d(x2_warp, w, strides=[1, 1, 1, 1], padding='SAME')

**Comment by Advocate99** [comment]
The tensorflow version is 1.8 gpu, as the readme said.
I try to replace tf.extract_image_patches, the error is the same.
Thank you for your replying.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Pengpeng Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 中午12:25
收件人:&nbsp;"ppliuboy/DDFlow"<DDFlow@noreply.github.com&gt;;
抄送:&nbsp;"zlt"<958602495@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ppliuboy/DDFlow] ERROR: could not initialize a memory descriptor (#9)





 
It seems that tf.extract_image_patches doesn't work for some tensorflow version. You can try replacing tf.extract_image_patches with another implementation, e.g.,
 out_channels = d * d w = tf.eye(out_channels*channel, dtype=tf.float32) w = tf.reshape(w, (d, d, channel, out_channels*channel)) x2_patches = tf.nn.conv2d(x2_warp, w, strides=[1, 1, 1, 1], padding='SAME')
